import { Category, Expense } from "@/types";

export const categories: Category[] = [
  {
    id: "cat-1",
    name: "Продукты",
    description: "Еда и напитки",
    color: "#22c55e",
    isActive: true,
  },
  {
    id: "cat-2",
    name: "Транспорт",
    description: "Такси и общественный транспорт",
    color: "#3b82f6",
    isActive: true,
  },
  {
    id: "cat-3",
    name: "Развлечения",
    description: "Кино, игры, подписки",
    color: "#f59e0b",
    isActive: true,
  },
  {
    id: "cat-4",
    name: "Одежда",
    description: "Одежда и обувь",
    color: "#ef4444",
    isActive: true,
  },
  {
    id: "cat-5",
    name: "Прочее",
    description: "Другие расходы",
    color: "#8b5cf6",
    isActive: true,
  },
  {
    id: "cat-6",
    name: "Здоровье",
    description: "Аптека и врачи",
    color: "#ec4899",
    isActive: true,
  },
  {
    id: "cat-7",
    name: "Образование",
    description: "Курсы и книги",
    color: "#14b8a6",
    isActive: true,
  },
  {
    id: "cat-8",
    name: "Кафе",
    description: "Рестораны и кафе",
    color: "#f97316",
    isActive: false,
  },
];

export const expenses: Expense[] = [
  {
    id: "exp-1",
    title: "Пицца",
    amount: 1200,
    date: "2025-01-10",
    note: "Доминос",
    categoryId: "cat-1",
  },
  {
    id: "exp-2",
    title: "Кофе",
    amount: 250,
    date: "2025-01-11",
    note: "Starbucks",
    categoryId: "cat-1",
  },
  {
    id: "exp-3",
    title: "Такси",
    amount: 600,
    date: "2025-01-12",
    note: "Яндекс Go",
    categoryId: "cat-2",
  },
  {
    id: "exp-4",
    title: "Кино",
    amount: 900,
    date: "2025-01-13",
    note: "IMAX",
    categoryId: "cat-3",
  },
  {
    id: "exp-5",
    title: "Футболка",
    amount: 1800,
    date: "2025-01-14",
    note: "H&M",
    categoryId: "cat-4",
  },
  {
    id: "exp-6",
    title: "Молоко и хлеб",
    amount: 320,
    date: "2025-01-15",
    note: "Пятёрочка",
    categoryId: "cat-1",
  },
  {
    id: "exp-7",
    title: "Метро",
    amount: 60,
    date: "2025-01-16",
    categoryId: "cat-2",
  },
  {
    id: "exp-8",
    title: "Spotify",
    amount: 199,
    date: "2025-01-17",
    note: "Подписка",
    categoryId: "cat-3",
  },
  {
    id: "exp-9",
    title: "Кроссовки",
    amount: 7500,
    date: "2025-01-18",
    note: "Nike",
    categoryId: "cat-4",
  },
  {
    id: "exp-10",
    title: "Витамины",
    amount: 850,
    date: "2025-01-19",
    note: "Аптека 36.6",
    categoryId: "cat-6",
  },
  {
    id: "exp-11",
    title: "Курс по TS",
    amount: 3990,
    date: "2025-01-20",
    note: "Udemy",
    categoryId: "cat-7",
  },
  {
    id: "exp-12",
    title: "Суши",
    amount: 2100,
    date: "2025-01-21",
    note: "Две палочки",
    categoryId: "cat-8",
  },
  {
    id: "exp-13",
    title: "Автобус",
    amount: 45,
    date: "2025-01-22",
    categoryId: "cat-2",
  },
  {
    id: "exp-14",
    title: "Книга",
    amount: 750,
    date: "2025-01-23",
    note: "Питер",
    categoryId: "cat-7",
  },
  {
    id: "exp-15",
    title: "Йогурт",
    amount: 180,
    date: "2025-01-24",
    note: "ВкусВилл",
    categoryId: "cat-1",
  },
  {
    id: "exp-16",
    title: "Бассейн",
    amount: 1200,
    date: "2025-01-25",
    note: "Абонемент",
    categoryId: "cat-6",
  },
  {
    id: "exp-17",
    title: "Шорты",
    amount: 1100,
    date: "2025-01-26",
    categoryId: "cat-4",
  },
  {
    id: "exp-18",
    title: "Uber",
    amount: 780,
    date: "2025-01-27",
    note: "Поездка в аэропорт",
    categoryId: "cat-2",
  },
  {
    id: "exp-19",
    title: "Netflix",
    amount: 799,
    date: "2025-01-28",
    note: "Подписка",
    categoryId: "cat-3",
  },
  {
    id: "exp-20",
    title: "Пельмени",
    amount: 420,
    date: "2025-01-29",
    note: "Лента",
    categoryId: "cat-1",
  },
  {
    id: "exp-21",
    title: "Зубная паста",
    amount: 290,
    date: "2025-01-30",
    note: "Oral-B",
    categoryId: "cat-5",
  },
  {
    id: "exp-22",
    title: "Карго-брюки",
    amount: 3200,
    date: "2025-01-31",
    note: "Zara",
    categoryId: "cat-4",
  },
];
